# Generated by Django 4.2.4 on 2023-12-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_22xxx', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='label',
            field=models.CharField(max_length=255),
        ),
    ]
