# Generated by Django 4.2.4 on 2023-12-04 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_22xxx', '0002_alter_module_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='total_cm',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='total_td',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='module',
            name='total_tp',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
