# Generated by Django 4.2.4 on 2023-12-04 15:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_22xxx', '0003_module_total_cm_module_total_td_module_total_tp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=5, unique=True)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='module',
            name='code',
            field=models.CharField(max_length=5, unique=True),
        ),
        migrations.AddField(
            model_name='module',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_22xxx.department'),
        ),
    ]
